from:
    Email: "pythonnea@python.org.ar"
    Name: "Organización Autodefensa Digital"
events:
    - name: AutoDefensa
      title: "Autodefensa Digital 2019"
      date: '2019-10-5'
categories:
  Attendee:
    fileprefix: Attendee
    description: Asistente
    regtype: person
  Collaborator:
    fileprefix: Collaborator
    description: Colaborador
    regtype: person
  Installer:
    fileprefix: Installer
    description: Instalador
    regtype: person
  Speaker:
    fileprefix: Activity
    description: Disertante
    regtype: activity
  Organizer:
    fileprefix: no
    description: Organizador
    regtype: no

